server-port=25565
difficulty=normal
gamemode=survival
max-players=50
view-distance=10
simulation-distance=8
online-mode=true
pvp=true
spawn-protection=16
level-type=minecraft\:normal
level-name=world
motd=Matrix Minecraft
white-list=true
enforce-whitelist=true
